feat: add node-test
qiwi/packasso pull request #53
Opened 2023-08-31 07:50 UTC by oljekechoro

2023-08-31 09:05 UTC, dimonka83 requested changes

2023-08-31 09:05 UTC, dimonka83 commented on packages/node-test/src/main/ts/bin.ts
> +            exclude: 'src/test',
лучше как в uvu портянка из src/main

2023-08-31 09:07 UTC, dimonka83 requested changes

2023-08-31 09:07 UTC, dimonka83 commented on packages/node-test/src/main/ts/bin.ts
> +      const files = await glob(`**/src/test/{ts,js}/**/*.${suffix}.{ts,js,tsx,jsx}`, { ignore: ['node_modules']})
тут надо глоб по пакетам, которые соответствуют пресету, т.е. по queuePackages надо глоб

2023-08-31 16:07 UTC, antongolub commented on packages/node-test/package.json
> +  "description": "node test",
The pkg description might be better.

2023-08-31 16:11 UTC, antongolub commented on packages/node-test/tsconfig.cjs.json
> +    "target": "es5",
es5 with esnext?

2023-09-01 06:27 UTC, dimonka83 requested changes

2023-09-01 06:27 UTC, dimonka83 commented on packages/node-test/package.json
> +  "version": "0.0.0",
2.0.0

2023-09-01 06:54 UTC, oljekechoro commented on packages/node-test/tsconfig.cjs.json
> +    "target": "es5",
тут так принято, отдельным коммитом пересмотрим настройки сборки

2023-09-01 07:00 UTC, dimonka83 approved these changes

2023-09-01 07:00 UTC, antongolub approved these changes

2023-09-01 07:09 UTC, merged